version: "3.7"
services:
  # server:
  #   build: .
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
